#!/bin/sh
set -e
case "$1" in
    remove|deconfigure)
        if [ -d /run/systemd/system ]; then
            if command -v deb-systemd-invoke >/dev/null 2>&1; then
                deb-systemd-invoke stop openlist-intranet.service || true
            else
                systemctl stop openlist-intranet.service || true
            fi
        fi
        ;;
esac
